#!/usr/bin/env bash
# Usage: pilot status <search>

set -e

# Provide pilot completions
if [ "$1" = "--complete" ]; then
  exec pilot-ls
elif [ -n "$1" ]; then
  SEARCH=$1
  PROGRAM_LABEL=`pilot resolve-label $SEARCH`
  GREP=`launchctl list | grep $PROGRAM_LABEL`
  if [ -n "$GREP" ]; then
    echo Running
  fi
fi