#!/usr/bin/env bash
set -e

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

libexec_path="$(abs_dirname "$0")"
export _PILOT_ROOT="$(abs_dirname "$libexec_path")"
export PATH="${libexec_path}:$PATH"

if [ -z "${PILOT_ROOT}" ]; then
  PILOT_ROOT="${HOME}/.pilot"
else
  PILOT_ROOT="${PILOT_ROOT%/}"
fi
export PILOT_ROOT

command="$1"
case "$command" in
"" )
  exec pilot-start
  ;;
"-h" | "--help" )
  exec pilot-help
  ;;
* )
  command_path="$(command -v "pilot-$command" || true)"
  if [ ! -x "$command_path" ]; then
    echo "pilot: no such command \`$command'" >&2
    exit 1
  fi

  shift
  exec "$command_path" "$@"
  ;;
esac
