#!/usr/bin/env bash
# Usage: pilot start [<program>]
# Summary: Start the given program or start all programs specified by manifests
#
# Help: When called with a program, that program will be started.
#
# When called with no arguments, Pilot will recursively climb the directory
# tree, finding all .pilot-manifest files, and start all programs declared in
# them.

set -e

# Provide pilot completions
if [ "$1" = "--complete" ]; then
  exec pilot-ls -a
elif [ -z "`pilot ls -a`" ]; then
  echo "You haven't installed any programs with pilot yet. Run 'pilot -h' to learn more."
else
  pilot control load $*
fi