#!/usr/bin/env bash
# Usage: pilot stop [<program>]
# Summary: Stop the given program or stop all programs specified by manifests
#
# Help: When called with a program, that program will be stopped.
#
# When called with no arguments, Pilot will recursively climb the directory
# tree, finding all .pilot-manifest files, and stop all programs declared in
# them.

set -e

# Provide pilot completions
if [ "$1" = "--complete" ]; then
  exec pilot-ls
else
  pilot control unload $*
fi