#!/usr/bin/env bash
# Usage: pilot resolve <search>

set -e

SEARCH="$1"

PROGRAM=$(
  ls ~/.pilot/programs |\
    grep -e "^$SEARCH$" -e "^$SEARCH.plist$" |\
    tail -n 1
)

if [ -n "$PROGRAM" ]; then
  echo $HOME/.pilot/programs/$PROGRAM
else
  exit 1
fi
