#!/usr/bin/env bash
# Usage: pilot start <program>

set -e

resolve_and_load_manifests() {
  directory=`pwd`
  programs=`pilot-resolve-manifests $directory`
  if [ -z "$programs" ]; then
    echo No program specified and no .pilot-manifest files found
    exit 1
  else
    for program in $programs; do
      echo Loading $program
      load_program $program
    done
  fi
}

load_program() {
  PROGRAM="$1"
  launchctl load -F `pilot-resolve $PROGRAM`
}

# Provide pilot completions
if [ "$1" = "--complete" ]; then
  exec pilot-ls
elif [ "$1" != "" ]; then
  load_program $1
else
  resolve_and_load_manifests
fi